"""per-watch shop

Revision ID: 90d3752320ad
Revises: b772979366c4
Create Date: 2026-09-01 16:00:53.378291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import bot.db.types  # пользовательские типы колонок (Money)


# revision identifiers, used by Alembic.
revision: str = '90d3752320ad'
down_revision: Union[str, Sequence[str], None] = 'b772979366c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('preferred_shops',
               existing_type=sa.VARCHAR(length=300),
               server_default=None,
               existing_nullable=False)

    with op.batch_alter_table('watches', schema=None) as batch_op:
        # server_default обязателен: колонка NOT NULL, а у существующих
        # отслеживаний значения нет. Пустая строка = «любой магазин».
        batch_op.add_column(
            sa.Column(
                'shop_key',
                sa.String(length=32),
                nullable=False,
                server_default='',
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watches', schema=None) as batch_op:
        batch_op.drop_column('shop_key')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('preferred_shops',
               existing_type=sa.VARCHAR(length=300),
               server_default=sa.text("('')"),
               existing_nullable=False)

    # ### end Alembic commands ###
