"""user preferred shops

Revision ID: b772979366c4
Revises: ed84db168b1b
Create Date: 2026-08-26 11:32:24.807305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import bot.db.types  # пользовательские типы колонок (Money)


# revision identifiers, used by Alembic.
revision: str = 'b772979366c4'
down_revision: Union[str, Sequence[str], None] = 'ed84db168b1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default обязателен: колонка NOT NULL, а у существующих
    # пользователей значения для неё нет. Пустая строка = «все магазины».
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'preferred_shops',
                sa.String(length=300),
                nullable=False,
                server_default='',
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('preferred_shops')

    # ### end Alembic commands ###
