"""initial schema

Revision ID: ed84db168b1b
Revises: 
Create Date: 2026-08-24 17:16:35.280033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import bot.db.types  # пользовательские типы колонок (Money)


# revision identifiers, used by Alembic.
revision: str = 'ed84db168b1b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('itad_id', sa.String(length=64), nullable=True),
    sa.Column('steam_appid', sa.Integer(), nullable=True),
    sa.Column('cheapshark_id', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_games_cheapshark_id'), ['cheapshark_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_games_itad_id'), ['itad_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_games_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_games_steam_appid'), ['steam_appid'], unique=True)
        batch_op.create_index(batch_op.f('ix_games_title'), ['title'], unique=False)

    op.create_table('shops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_shops_source_external')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('notify_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_tg_id'), ['tg_id'], unique=True)

    op.create_table('price_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('price', bot.db.types.Money(), nullable=False),
    sa.Column('regular_price', bot.db.types.Money(), nullable=True),
    sa.Column('cut', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('price_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_snapshots_checked_at'), ['checked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_price_snapshots_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_price_snapshots_shop_id'), ['shop_id'], unique=False)
        batch_op.create_index('ix_snapshots_game_checked', ['game_id', 'checked_at'], unique=False)

    op.create_table('watches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('target_price', bot.db.types.Money(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('notify_any_drop', sa.Boolean(), nullable=False),
    sa.Column('last_notified_price', bot.db.types.Money(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'game_id', name='uq_watches_user_game')
    )
    with op.batch_alter_table('watches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watches_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_watches_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watches_user_id'))
        batch_op.drop_index(batch_op.f('ix_watches_game_id'))

    op.drop_table('watches')
    with op.batch_alter_table('price_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_snapshots_game_checked')
        batch_op.drop_index(batch_op.f('ix_price_snapshots_shop_id'))
        batch_op.drop_index(batch_op.f('ix_price_snapshots_game_id'))
        batch_op.drop_index(batch_op.f('ix_price_snapshots_checked_at'))

    op.drop_table('price_snapshots')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_tg_id'))

    op.drop_table('users')
    op.drop_table('shops')
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_games_title'))
        batch_op.drop_index(batch_op.f('ix_games_steam_appid'))
        batch_op.drop_index(batch_op.f('ix_games_slug'))
        batch_op.drop_index(batch_op.f('ix_games_itad_id'))
        batch_op.drop_index(batch_op.f('ix_games_cheapshark_id'))

    op.drop_table('games')
    # ### end Alembic commands ###
